WIN_MIN_WIDTH = 800
WIN_MIN_HEIGHT = 600
WIN_WIDTH = 1024
WIN_HEIGHT = 768
WIN_BG_COLOR = "#282c34"
WIN_SPLIT = 0.3
LEFT_FRAME_COLOR = "#282c34"
RIGHT_FRAME_COLOR = "white"
APP_NAME = "Clothing Auto-Modeler"
LOGO_PATH = "./img/logo.png"
BUTTON_COLOR = "#4070f5"
PROGRESS_BAR_COLOR = "#4070f5"
PROGRESS_BAR_BG = "#F0F0F0"
BUTTON_FOCUS_COLOR = "#4055f5"
ABOUT_TEXT = "Group project for 24671 Electromechanical Systems Design course offered by Carnegie Mellon University in the Spring of 2020. This is a collective work by Justin Tunis, Shu You, and Allen Jiang."
SETTING_BG_COLOR = "#282c34"
ENTRY_COLOR = "#F0F0F0"
FRAME_BORDER_COLOR = "#F0F0F0"
CANCEL_BUTTON_COLOR = "#F0F0F0"
CANCEL_BUTTON_FOCUS_COLOR = "#C8C8C8"
PREVIEW_IMG_PATH = "./img/verticalplaceholderimage-440x680.png"
IMAGE_WIDTH_CAP = 300
IMAGE_HEIGHT_CAP = 400
MAX_CHAR_LEN = 20
